{{- if .Values.argo.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: {{ .Values.argo.namespace | default .Values.kubernetes.namespace }}
  labels:
    {{- include "scaleodm.labels" . | nindent 4 }}
    app.kubernetes.io/component: workflow-controller
data:
  {{- if .Values.argo.controller.parallelism }}
  parallelism: {{ .Values.argo.controller.parallelism | quote }}
  {{- end }}
{{- end }}

