{{- if and (not .Values.argo.enabled) .Values.argo.controller.parallelism }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: {{ .Values.argo.namespace | default .Values.kubernetes.namespace }}
  labels:
    {{- include "scaleodm.labels" . | nindent 4 }}
    app.kubernetes.io/component: workflow-controller
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
data:
  parallelism: {{ .Values.argo.controller.parallelism | quote }}
{{- end }}


