{{- if .Values.kubernetes.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scaleodm.serviceAccountName" . }}
  labels:
    {{- include "scaleodm.labels" . | nindent 4 }}
  {{- with .Values.kubernetes.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

