name: ðŸš€ Release Image

on:
  release:
    types: [published]

permissions:
  packages: write  # Required for nested job in image_build workflow

jobs:
  prep:
    runs-on: ubuntu-latest
    outputs:
      repo: ${{ steps.set_repo.outputs.repo }}
    steps:
      - name: Lowercase GITHUB_REPOSITORY
        id: set_repo
        run: |
          repo=$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')
          echo "repo=$repo" >> "$GITHUB_OUTPUT"

  container-img:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@2.0.5
    with:
      build_target: release
      image_name: ghcr.io/${{ needs.prep.outputs.repo }}
